services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "cpidb1"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  web:
    build: ./app
    container_name: flask_app_container
    restart: always
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=cpidb1
      - SESSION_KEY=${SESSION_KEY}
    volumes:
      - ./app:/app
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf # change between dev and prod
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    networks:
      - internal

volumes:
  mysql_data:

networks:
  internal:
    driver: bridge