CREATE DATABASE IF NOT EXISTS `cpidb1`;
USE `cpidb1`;

DROP TABLE IF EXISTS `questions`;
CREATE TABLE `questions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `question` text,
  `option1` text,
  `option2` text,
  `option3` text,
  `option4` text,
  `option5` text,
  `option6` text,
  `correct` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=255 DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `password` varchar(60) DEFAULT NULL,
  `totalanswered` int DEFAULT NULL,
  `totalcorrect` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `user_question`;
CREATE TABLE `user_question` (
  `user_id` int NOT NULL,
  `question_id` int NOT NULL,
  `lastattemptdate` date DEFAULT NULL,
  `attempts` int DEFAULT NULL,
  `correct` int DEFAULT NULL,
  PRIMARY KEY (`user_id`,`question_id`),
  KEY `question_id` (`question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (1, "Your client is considering implementing S/4HANA in the cloud and is not sure which deployment option is the best fit. They need the full functional scope of SAP S/4HANA along with the ability to customize, modify, and extend it. What cloud deployment option satisfies these requirements?", "1.) SAP S/4HANA Cloud, private option", "2.) SAP S/4HANA private managed cloud", "3.) SAP S/4HANA Cloud", "4.) SAP S/4HANA", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (2, "In SAP Integration Advisor, how can you group related information into reusable segments?", "1.) By creating matching groups for nodes", "2.) By qualifying nodes", "3.) By assigning code lists to the leaf nodes", "4.) By providing multiple payload data sets", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (3, "Your iFlow has diverged into multiple branches. You want to merge these branches into one common branch. Which of the following routing options can you use?", "1.) Aggregator", "2.) Gather", "3.) Join", "4.) Multicast", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (4, "Your client has a requirement that end users need to see analytic content in the form of charts and tiles. What service in SAP Cloud Platform does this \"out of the box\" without the need for coding?", "1.) SAP Streaming Analytics", "2.) SAP HANA Advance Analytics", "3.) SAP Predictive service", "4.) SAP Smart Business service", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (5, "Which settings can you use to connect to twitter? (2 correct)", "1.) Use Request and Reply with HTTP adapter", "2.) Use only the Twitter outbound adapter", "3.) Use Request and Reply with Twitter outbound adapter", "4.) Use RFC adapter to connect directly to twitter", NULL, NULL, "1,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (6, "You develop an app using the SAP Cloud Application Programming Model (CAP). What do you use to define the data model?", "1.) Core Data Services (CDS)", "2.) SAP Cloud SDK", "3.) SAP Cloud Platform SDK", NULL, NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (7, "Which SAP Cloud Integration process step allows you to run iFlows directly after deployment?", "1.) Message Digest", "2.) Content Modifier", "3.) Scheduler", "4.) Timer", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (8, "At what levels do you secure message exchange? (2 correct)", "1.) Message", "2.) Deployment", "3.) Transport", "4.) Runtime", NULL, NULL, "1,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (9, "Which ISO codes are supported in SAP Integration Advisor code lists? (3 correct)", "1.) Industry codes", "2.) Currency codes", "3.) Territory codes", "4.) Language codes", "5.) Country codes", NULL, "2,4,5");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (10, "Why does the API Management capability of the SAP Integration Suite require API providers?", "1.) To incorporate APIs from other systems", "2.) To create authenticated API instances", "3.) To create new custom APIs", NULL, NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (11, "You split a message, modify the split message, merge the split message and send in a single message via a Web Service. What are the steps to accomplish this?", "1.) 1- Split 2- Multicast 3- Aggregator 4- SEND", "2.) 1- Split 2- Aggregator 3- Join 4- SEND", "3.) 1- Split 2- SEND", "4.) 1- Split 2- Join 3- Gather 4- SEND", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (12, "You want to develop an SAP HANA extended application services, advanced model app. What can you use to define the database layer?", "1.) Java Persistence API layer for SAP HANA (JPA)", "2.) SAP HANA Deployment Infrastructure (HDI)", "3.) SAP HANA SQL", "4.) Core Data Services for SAP S/4HANA (CDS)", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (13, "Which of the following are process templates of SAP's Intelligent Enterprise? (2 correct)", "1.) Design-to-Cash", "2.) Lead-to-Cash", "3.) Lead-to-Pay", "4.) Design-to-Operate", NULL, NULL, "2,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (14, "What are approaches to develop a REST API? (2 correct)", "1.) Contract First", "2.) Code First", "3.) Protocol First", "4.) Schema First", NULL, NULL, "1,2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (15, "When you build an iFlow, what can you do to handle errors?", "1.) Implement an exception handler iFlow element", "2.) Place artifacts into a TRY-CATCH subprocess", "3.) Create an exception-handling subprocess", "4.) Use a condition to check status codes", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (16, "Which usage options are offered by SAP Cloud Platform Integration? (2 correct)", "1.) Value mapping", "2.) SOAP service", "3.) Data migration", "4.) OData service", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (17, "Which of the following tools can you use to set up secure communication between an SAP on- premise system and the SAP Cloud Platform?", "1.) SAP Cloud Platform Integration Suite", "2.) SAP Cloud Platform Open Connector", "3.) SAP API Management", "4.) SAP Cloud Connector", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (18, "Where do you find information about APIs built by partners and SAP?", "1.) SOA Manager", "2.) Enterprise Service Repository", "3.) SAP Cloud Platform API Management", "4.) SAP API Business Hub", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (19, "Why must an instance in SAP Open Connectors be authenticated?", "1.) To build a custom connector to connect with an API provider", "2.) To view the respective connector's API Docs", "3.) To access the data in the associated third-party service tenant", NULL, NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (20, "What is an advantage of the consumption-based commercial model over the subscription-based commercial model?", "1.) Customers pay a fixed price upfront for the services they plan to use.", "2.) Customers can use all services paying a flat fee.", "3.) Services can be used with service-specific commitment.", "4.) Services can be used without service-specific commitment.", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (21, "In what order do you set up outbound communication via HTTP to an on Prem back-end system? (2 correct)", "1.) 1. SAPCPI 2. Web dispatcher 3. HTTP Interface", "2.) 1. SAPCPI 2. SAP cloud Connector 3. HTTP Interface", "3.) 1. SAPCPI 2. HTTP Interface", "4.) 1. SAP CPI 2. SAP Business Connector 3. HTTP Interface", NULL, NULL, "2,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (22, "Which of the following is a publicly managed SAP solution?", "1.) SAP S/4HANA Cloud, extended edition", "2.) SAP S/4HANA Cloud, essentials edition", "3.) SAP HANA Enterprise Cloud", NULL, NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (23, "You have created an SAP Open Connectors instance and want to create a product from it in API Management. Which sequence of steps must you perform?", "1.) Create a Product. Create an API Provider. Create an API Proxy.", "2.) Create a Product. Create an API Proxy. Create an API Provider.", "3.) Create an API Provider. Create an API Proxy. Create a Product.", "4.) Create an API Proxy. Create an API Provider. Create a Product.", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (24, "What can you use to develop a microapp? (2 correct)", "1.) SAP HANA extended application services, classic model", "2.) SAP ABAP RESTful programming model", "3.) SAP HANA extended application services, advanced model", "4.) SAP Cloud Application Programming Model (CAP)", NULL, NULL, "2,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (25, "What are the optimal integration domains for SAP Cloud Platform Integration? (2 correct)", "1.) OnPremise20nPremise", "2.) OnPremise2Cloud", "3.) Cloud2Cloud", "4.) Thing2Cloud", NULL, NULL, "2,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (26, "Your client asks you to identify a few features of SAP S/4HANA, private option. Which of the following are features? (2 correct)", "1.) Half-year release cycle", "2.) Annual release cycle", "3.) Subscription licensing", "4.) Bring your own license (BYOL)", NULL, NULL, "2,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (27, "What are components of the SAP Intelligent Enterprise Framework? (3 correct)", "1.) Intelligent Technologies", "2.) Intelligent Services", "3.) Digital Deployment", "4.) Intelligent Suite", "5.) Digital Platform", NULL, "1,4,5");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (28, "In SAP Cloud Integration, what do you use to modify a message body? (2 correct)", "1.) Python", "2.) Groovy Script", "3.) Mapping", "4.) Content Modifier", NULL, NULL, "2,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (29, "Which of the following adapter types can you use for iFlow-to-iFlow communication?", "1.) RFC", "2.) OData", "3.) ProcessDirect", "4.) JMS", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (30, "Which databases are supported by SAP Cloud Platform data and storage services? (3 correct)", "1.) SAP MaX DB", "2.) Apache Couch DB", "3.) Redis on SAP Cloud Platform", "4.) SAP HANA", "5.) Postgre SQL on SAP Cloud Platform", NULL, "3,4,5");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (31, "Which technology is part of SAP's digital innovation system?", "1.) Microservices", "2.) Containers", "3.) Internet of Things", "4.) Analytics", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (32, "You design a process to throw an exception while messages are being processed by the SAP Cloud Platform Integration service. What iFlow step type does this?", "1.) Error Start", "2.) Error End", "3.) Terminate Message", "4.) Escalation Ends", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (33, "What are some features of SAP Cloud Integration? (2 correct)", "1.) Versioning of iFlow packages", "2.) Exporting iFlow packages", "3.) Versioning of iFlow artifacts", "4.) Exporting of iFlow steps", NULL, NULL, "2,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (34, "To subscribe to the Integration Suite service in an SAP BTP trial account, which identifier is required?", "1.) Space", "2.) Instance", "3.) Plan", "4.) App", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (35, "What pattern is NOT contained in a Camel Exchange Message?", "1.) Runtime node information", "2.) In Message", "3.) Exchange ID", "4.) Exception", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (36, "You are implementing an iFlow and need an adapter that is not available in the Adapter Type selection dialog. Which of the following options can you use to find additional adapters? (2 correct)", "1.) SAP API Business Hub", "2.) SAP Discovery Center", "3.) SAP Tutorial Navigator", "4.) Discover function in SAP Cloud Integration", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (37, "In SAP Cloud Integration, what encoding schemes can you use to encode messages? (2 correct)", "1.) MIME Multipart Encoder", "2.) Hex Encoder", "3.) HTML Encoder", "4.) ZIP Compression", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (38, "Which of the following hyperscalers run SAP Business Technology Platform? (2 correct)", "1.) IBM Cloud", "2.) Amazon Web Services", "3.) Microsoft Azure", "4.) VMware", NULL, NULL, "2,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (39, "What tool is used to perform extension on SAP S/4Hana Cloud?", "1.) SAP Net weaver Developer Studio (NWDS)", "2.) SAP Web IDE Full-Stack", "3.) SE80", "4.) OData", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (40, "Where can you find and subscribe to SAP BTP SaaS applications?", "1.) Service Marketplace", "2.) Cloud Foundry", "3.) SAP Discovery Center", NULL, NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (41, "What are the building blocks of the SAP Cloud Application Programming model (CAP)? (2 correct)", "1.) SAP Cloud SDK", "2.) Custom business objects", "3.) Core Data Services", "4.) SAP Cloud Platform SDK", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (42, "What describes the basic principles of SAP Leonardo?", "1.) Is a design-lead approach to combine cloud and on premise solutions.", "2.) Is a Is a design-lead approach to innovation?", "3.) Is a renaming of multi-cloud structures?", NULL, NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (43, "In SAP Cloud Integration, which iFlow element can use a namespace?", "1.) Mapping", "2.) Timer", "3.) Script", "4.) Filter", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (44, "What is the SAP Smart Business service?", "1.) A framework for supporting projects", "2.) A framework for visualizing analytic content in the form of charts and tiles", "3.) A framework for geocoding", "4.) A framework for extended data cleansing", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (45, "An HTTPS GET call using /$metadata suffixed to the URL provides the result of the call in JSON format. Which API was used? (2 correct)", "1.) IDoc API", "2.) OData API", "3.) REST API", "4.) SOAP API", NULL, NULL, "2,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (46, "Which of the following mapping artifacts can be shared between SAP Process Integration and SAP cloud Platform Integration? (2 correct)", "1.) ABAP Mapping", "2.) Message Mapping", "3.) Java Mapping", "4.) Operation Mapping", NULL, NULL, "2,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (47, "What is used to define reusable composed message structures in a Message Implementation Guideline (MIG)?", "1.) Type Systems", "2.) Complex Types", "3.) Qualifiers", "4.) Simple Types", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (48, "What information does SAP provide through the SAP API Business Hub? (2 correct)", "1.) Events", "2.) Integration content", "3.) Data schemata", "4.) IDoc definitions", NULL, NULL, "1,2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (49, "You want to avoid manually altering iFlows to accommodate changes in values. How can you do this?", "1.) Use targeted externalization of changing values", "2.) Add the changing values as resources in the integration flow configuration", "3.) Add a content enricher process step for changing values", "4.) Set the changing exchange property values within process steps", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (50, "What kind of cloud solution is SAP HANA Enterprise Cloud?", "1.) On-premises managed", "2.) Hybrid managed", "3.) Public managed", "4.) Private managed", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (51, "Which of the following is a valid sequence of activities in SAP Integration Suite?", "1.) Connect third-party API in SAP Open Connectors. Make API accessible in API Management. Use API in iFlow in Cloud Integration", "2.) Connect third-party API in API Management. Make API accessible in Integration Advisor. Use API in iFlow in SAP Open Connectors", "3.) Connect third-party API in Cloud Integration. Make API accessible in SAP Open Connectors. Use API in iFlow in API Management", NULL, NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (52, "While testing your iFlow, you notice that messages are being received but not processed, due to a problem with the user. The error the log reads as follows: \"com.sap.esb.application.services.cxf.interceptor.SimpleAuthorizinglnterceptor user is not authorized\". What should you do to fix this error?", "1.) Redeploy the known hosts in the tenant key store.", "2.) Redeploy the X.509 certificate in the tenant keystore for the user.", "3.) Assign the ESBMessaging.send.role to the user.", "4.) Change the method of authentication from Basic to Certificate to the user.", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (53, "You want to perform content-specific filtering of a message. Which value types can you use? (2 correct)", "1.) String", "2.) Byte", "3.) Double", "4.) Nodelist", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (54, "What are some of the core capabilities of the SAP Integration Suite? (2 correct)", "1.) Connectivity service", "2.) API Management", "3.) SAP Business Application Studio", "4.) Open Connectors", NULL, NULL, "2,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (55, "How is a message mapping created in SAP Integration Advisor? (MIG: Message Implementation Guideline, MAG: Mapping Guideline)", "1.) Create MAG. Choose correct type system. Create Target MIG. Create Source MIG", "2.) Create MAG. Choose correct type system. Create Source MIG. Create Target MIG", "3.) Create Target MIG. Create Source MIG. Choose correct type system. Create MAG", "4.) Choose correct type system. Create Source MIG. Create Target MIG. Create MAG", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (56, "What authentication method is used with the Monitoring API?", "1.) Single sign-on (SSO)", "2.) Basic authentication", "3.) Two-factor authentication", "4.) OAuth2", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (57, "Your client requests an SAP Cloud Platform Integration tenant from SAP and one is provided. As part of the tenant onboarding process, several application URIs are provided to your client. Which of the URIs below is for the SOAP adapter on the runtime node?", "1.) https://customer.specific.url.hana.ondemand.com/cxf", "2.) https://customer.specific.url.hana.ondemand.com/http", "3.) https://customer.specific.url.hana.ondemand.com/gw", NULL, NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (58, "Which of the following are integrated solutions of SAP's Business Technology Platform? (2 correct)", "1.) Blockchain", "2.) Development and Deployment", "3.) Analytics", "4.) Application Development and Integration", NULL, NULL, "3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (59, "You use a Local Call > Looping Process Call and the value of the Expression Type is Non-XML. What expression language can you use? (2 correct)", "1.) Camel Simple Expression language", "2.) Spring Expression Simple", "3.) EL Expression Language", "4.) Unified Expression Language", NULL, NULL, "1,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (60, "Which of the following can you connect with SAP Integration Suite Open Connectors?", "1.) The SAP Business Technology Platform with non-SAP cloud applications", "2.) Non-SAP cloud applications with SAP on-premise systems", "3.) The SAP Business Technology Platform with SAP on-premise systems", NULL, NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (61, "You want to forward a notification (asynchronous) to a back-end system. What option can you use?", "1.) Content Enricher", "2.) Send", "3.) Process Call", "4.) Request Reply", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (62, "Your caller sends only a decrypted message payload. Which security standard can use to encrypt this message payload? (2 correct)", "1.) XML Signature", "2.) Web Services Security (WS-Security)", "3.) HIPAA secure messaging", "4.) Open Pretty Good Privacy (Open PGP)", NULL, NULL, "2,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (63, "What is the relationship between an API Provider and an API Proxy in API Management?", "1.) The API Proxy acts as a proxy for all API instances provided through the API Provider.", "2.) The API Provider provides a URL for an API instance provided through the API Proxy.", "3.) The API Proxy provides a URL for an API instance provided through the API Provider.", NULL, NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (64, "What are the main architecture layers of the SAP Cloud Stack? (3 correct)", "1.) BaaS", "2.) SaaS", "3.) PaaS", "4.) DaaS", "5.) IaaS", NULL, "2,3,5");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (65, "What can you search using SAP Open Connectors Query Language (OCNQL)?", "1.) Instances created in SAP Open Connectors", "2.) Data provided by APIs in SAP Open Connectors", "3.) Connectors provided in SAP Open Connectors", NULL, NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (66, "Which of the following describe the functionality of a polling sender adapter? (2 correct)", "1.) Non-configurable execution schedule", "2.) Only one execution at a time", "3.) Configurable execution schedule", "4.) Multiple executions at a time", NULL, NULL, "2,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (67, "Your client has a requirement that front-level service reps need role-based tiles hosted in SAP Fiori launchpad that show real-time temperature change readings coming from sensors placed in thermometers. What SAP Cloud Platform service do you recommend?", "1.) SAP Leonardo Machine Learning", "2.) SAP HANA for advanced analytics: Search, Text Analysis, and Mining", "3.) SAP Smart Business service", "4.) SAP HANA advanced analytics: Predictive Analytics", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (68, "How do you configure a SSL outbound communication with HTTP?", "1.) Import the Receiver Client Certificate in Operations > Manage Security > Security Material", "2.) Import the Receiver Server Certificate in Operations > Manage Security > Security Material", "3.) Import the Receiver Server Certificate in Operations > Manage Security > Manage Key store", "4.) Import the Receiver Client Certificate in Operations > Manage Security > Manage Key store", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (69, "Which of the following are features of digital business transformation? (3 correct)", "1.) Perpetual license agreements", "2.) Resource pooling", "3.) Adaptive and Scalable operating model", "4.) Simplified IT landscape", "5.) Reduced time to realize business value", NULL, "3,4,5");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (70, "What criterion can you use to select fitting mapping proposals?", "1.) Qualified variations", "2.) Confidence score", "3.) Constraints", NULL, NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (71, "Your client asks for advice regarding which SAP Cloud Platform service they should use placed in devices. Which SAP Cloud Platform service should they use?", "1.) SAP Cloud Platform OData Provisioning", "2.) SAP HANA smart data integration", "3.) RabbitMQ on SAP Cloud Platform", "4.) SAP API Business Hub", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (72, "A user needs read-only access to the Data Store Viewer. What authorization group must be assigned to this user? (2 correct)", "1.) AuthGroup.Administrator", "2.) AuthGroup.IntegrationDeveloper", "3.) AuthGroup.SystemDeveloper", "4.) AuthGroup.BusinessExpert", NULL, NULL, "3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (73, "You have to process an inbound EDIFACT message to an outbound SAP IDoc. Therefore, you have to map the EDIFACT message to the IDoc message in your iflow. What tool can you use?", "1.) SAP HANA studio", "2.) SAP Web IDE Full-Stack", "3.) SAP NetWeaver Developer Studio n Integration content advisor", NULL, NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (74, "You want to use a XSLT mapping in your iFlow. You want to use dynamic parameters that are set as exchange message properties. How can you do this?", "1.) Use Java script within a special namespace in the XSL template.", "2.) Use only dynamic parameters in the content modifier artifact.", "3.) Use simple expression language within a special namespace in the XSL template.", NULL, NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (75, "Which of the following environments are available in the SAP Business Technology Platform? (3 correct)", "1.) Kyma environment", "2.) Cloud Foundry environment", "3.) ABAP environment", "4.) Netweaver environment", "5.) Kubernetes environment", NULL, "1,2,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (76, "What are some advantages of the SAP Cloud Integration? (2 correct)", "1.) Installation is not required", "2.) Offline development", "3.) Development of Customer-to-Customer (C2C) integrations", "4.) Out-of-the-box usage of predefined scenarios", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (77, "You are designing an iFlow and one of the requirements is to merge separate messages from different paths in the iFlow into one message. What step type should you use?", "1.) Gather", "2.) Multicast", "3.) Router", "4.) Aggregator", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (78, "What are some tasks of an App Router? (2 correct)", "1.) Acts as a reverse proxy", "2.) Manages authorization flows", "3.) Manages authentication flows", "4.) Generates JSON tokens", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (79, "You want to use cloud services from SAP. You want your data to be secured and stored exclusively by you. Which of the deployment models can you use? (3 correct)", "1.) Private cloud", "2.) Analytical cloud", "3.) Public cloud", "4.) Fiori cloud", "5.) Hybrid cloud", NULL, "1,3,5");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (80, "Which of the following transformation steps can you use to add message headers to an iFlow message?", "1.) Content Modifier", "2.) Converter", "3.) Decoder", "4.) EDI Extractor", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (81, "Which programming language can you use to developing-app extensibility?", "1.) Node.js", "2.) abap", "3.) Java", NULL, NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (82, "Runtime artifacts generated by SAP Integration Advisor can be used in which middleware and runtime solutions? (2 correct)", "1.) SAP Cloud Integration", "2.) SAP S/4HANA Cloud", "3.) SAP S/4HANA", "4.) SAP Process Orchestration", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (83, "You need to encrypt the contents of a message. What encryptor should you use?", "1.) SFTP", "2.) AES", "3.) HTTPS", "4.) PGP", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (84, "One of the requirements of the project you are working on is to store data in JSON format without the need for static schemas or data extraction via SQL. What solution should you use to satisfy this requirement?", "1.) Node.js", "2.) PostgreSQL on SAP Cloud Platform", "3.) Redis on SAP Cloud Platform", "4.) SAP HANA", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (85, "Where can you find an overview of the SAP Business Technology Platform services that you can subscribe to?", "1.) In SAP API Business Hub", "2.) In SAP API Management", "3.) In the SAP Discovery Center", "4.) In the SAP Voyager Center", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (86, "What is the main role of the SAP Cloud Platform Integration Service?", "1.) It integrates a customer's own application landscape with a private cloud.", "2.) It integrates cloud applications into an application landscape.", "3.) It integrates a customer's own application landscape with a public cloud.", "4.) It integrates on premise apps with mobile app.", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (87, "What are some characteristics of a distributed system? (2 correct)", "1.) Connected computers appear connected through SAP Cloud Platform, Cloud Foundry environment.", "2.) Individual computers are connected through a network.", "3.) Individual computers are connected through Kubernetes.", "4.) Connected computers appear as a single computer.", NULL, NULL, "2,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (88, "What is used to perform extension for SAP Ariba?", "1.) OData API", "2.) SAP Web IDE Full-Stack", "3.) cXML", "4.) Rest API", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (89, "What is an SAP Integration Suite capability to establish connectivity with third-party applications? (2 correct)", "1.) SAP Connectivity service", "2.) SAP Open Connectors", "3.) SAP Cloud Integration", "4.) SAP Cloud Connector", NULL, NULL, "2,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (90, "Which of the following are Twelve Factor application principles? (2 correct)", "1.) Do not strictly separate build and run stages", "2.) One code base tracked in revision control, one deploy", "3.) Strictly separate build and run stages", "4.) One code base tracked in revision control, many deploys", NULL, NULL, "3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (91, "What cloud deployment model does SAP Cloud Platform follow?", "1.) Public", "2.) Private", "3.) On premise", NULL, NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (92, "What can you use to add business logic to SAP S/4HANA Cloud? (2 correct)", "1.) ln-app extensibility", "2.) Extensibility services on SAP Cloud Platform", "3.) Side-by-side extensibility", "4.) SAP Enterprise Messaging", NULL, NULL, "1,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (93, "Which of the following content categories are available on SAP API Business Hub? (3 correct)", "1.) Integrations", "2.) ABAP packages", "3.) Database tables", "4.) APIs", "5.) Business Processes", NULL, "1,4,5");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (94, "Your client has a requirement that all new reporting apps are to be deployed on SAP Cloud Platform, but those apps will access data from existing on premise systems via secure tunnels. They do not wish to use an SAP Gateway server to implement this access. What SAP Cloud Platform service eliminates the need for an SAP Gateway server for on premise data access?", "1.) SAP API Business Hub", "2.) SAP Cloud Platform Connectivity", "3.) SAP Cloud Platform OData Provisioning", "4.) SAP Cloud Platform API Management", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (95, "What can you use to test a standard OData interface?", "1.) An in-app extension", "2.) The SAP API Business Hub", "3.) A side-by-side extension", "4.) An SAP Gateway service on SAP Cloud Platform", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (96, "What can you select as a source to create an API in SAP Open Connectors? (2 correct)", "1.) API Provider", "2.) Product", "3.) API Business Hub Enterprise Page", "4.) API Proxy", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (97, "What are the advantages of implementing local integration processes? (2 correct)", "1.) Limit complexity", "2.) Decrease modularization", "3.) Boost performance", "4.) Increase readability", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (98, "You want to use inbound SOAP adapter for asynchronous communication. Which configuration is available in the Connection tab? (2 correct)", "1.) Manual as Service Definition and one way as Message exchange Pattern", "2.) Manual as Service Definition and the sender defines the asynchronous communication", "3.) Manual as Service Definition and Request-Replay as Message Exchange Pattern", "4.) WSDL as Service Definition with additional entries", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (99, "What is NOT composed in a sequence of packets in a PGP message?", "1.) Signature", "2.) Public Key", "3.) Literal data", "4.) Integration flow ID", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (100, "What feature applies to a SaaS application?", "1.) Hardware license must be issued before the application can be used", "2.) Delivered over the Internet", "3.) Delivered via software bundle in a box", "4.) Different version of the application can be used", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (101, "You are new to the SAP BTP. Which of the following models are best suited for exploring SAP Business Technology Platform capabilities? (2 correct)", "1.) SAP BTP Trial", "2.) Free Tier Model", "3.) Cloud Platform Enterprise Agreement", "4.) PayAsYouGo", NULL, NULL, "1,2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (102, "You have an asynchronous integration scenario. Which adapters enable asynchronous messaging? (2 correct)", "1.) JMS", "2.) LDAP", "3.) ODC", "4.) IDoc", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (103, "In SAP Cloud Integration, which data format is accepted by the Filter process step?", "1.) HTTP", "2.) XML", "3.) CSV", "4.) JSON", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (104, "Which of the following tools can you use to secure an OData interface? (2 correct)", "1.) SAP API Management", "2.) SAP Remote Access and Connectivity service", "3.) SAP Cloud Connector", "4.) SAP Cloud Platform Integration", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (105, "You want to direct messages along a specific path using an expression. What element do you use?", "1.) Router", "2.) Splitter", "3.) Join", "4.) Aggregator", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (106, "Which of the following are elements of an X.509 certificate? (2 correct)", "1.) Adapter profile", "2.) Issuer", "3.) Distinguished name", "4.) Communication rule", NULL, NULL, "2,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (107, "According to the National Institute of Standard and Technology (NIST), which of the following are key characteristics of cloud computing? (2 correct)", "1.) Measured service", "2.) Own infrastructure", "3.) Limited elasticity", "4.) Resource pooling", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (108, "You want to detect errors while message processing but without a Message Failed status. Which events can you use? (2 correct)", "1.) Message End Event in an Exception Sub process", "2.) Escalation Event in an Exception Sub process", "3.) Exception Message in an Exception Sub process", "4.) Terminate Message in an Exception Sub process", NULL, NULL, "1,2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (109, "Which of the following components are part of the SAP Cloud Platform Integration Suite? (2 correct)", "1.) SAP API Business Hub", "2.) Process Integration", "3.) Integration Advisor", "4.) API Management", NULL, NULL, "3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (110, "What do service-related missions in the SAP Discovery Center contain?", "1.) Learning games designed to train developers in SAP software", "2.) Best practices and step-by-step guidance for implementing business use cases", "3.) Ready-to-run integration flows for your business use cases", NULL, NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (111, "What are some benefits of value externalization in iFlows? (2 correct)", "1.) Separation of business logic from iFlows", "2.) Faster run time of iFlows", "3.) Less memory consumption of iFlows", "4.) Simplified portability of iFlows between different tenants", NULL, NULL, "1,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (112, "You assign a user to the AuthGroup. Business Expert Group. What specific task can this user perform? (3 correct)", "1.) Delete messages from the transient data store", "2.) Deploy integration content", "3.) Manage security artifacts", "4.) Access (read only) the data store viewer", "5.) Read the message payload and attachments", NULL, "3,4,5");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (113, "What actions can you perform in an SAP BTP trial account? (2 correct)", "1.) Assign users to a global account", "2.) Create global accounts", "3.) Create subaccounts", "4.) Assign users to a subaccount", NULL, NULL, "3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (114, "To which concept do OData entities correspond?", "1.) Typed classes", "2.) Packages", "3.) Untyped classes", "4.) Class properties", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (115, "In a mail receiver adapter you use plain user/password for authentication. Where do you define the user and password?", "1.) Manage Security Material > User Credentials", "2.) Manage Security Material > Secure Parameter", "3.) Create directly as user and password at the mail receiver adapter configuration", "4.) Manage Security Material > OAuth2 Credentials", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (116, "Your iflow receives a JSON inbound message. The outbound message should also be JSON, but structurally different from the inbound message. What steps can you perform? (2 correct)", "1.) 1- Convert JSON2XML 2- Message Mapping 3- Convert XML2JSON", "2.) 1- Convert JSON2XML 2- Message Mapping 3- Convert JSON2XML", "3.) 1- Convert XML2JSON 2- Message Mapping 3- Convert JSON2XML", "4.) 1- Convert JSON2XML 2- XSLT Mapping 3- Convert XML2JSON", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (117, "You want to create an API Proxy for a third-party API but cannot discover any API in the dialog. Which of the following steps might you have forgotten?", "1.) Create a Product for the required API.", "2.) Create an API Key policy.", "3.) Add an API Provider for SAP Open Connectors.", "4.) Add an API Provider for Cloud Integration.", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (118, "You want to grant a new developer access to a service hosted on an SAP Cloud Platform Integration tenant. Where do you this?", "1.) SAP Cloud Platform", "2.) SAP ID service", "3.) SAP Solution Manager", "4.) SAP Cloud Platform Integration tenant setting", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (119, "Which iFlow element in SAP Cloud Integration do you use to send a message to more than one recipient?", "1.) Gather", "2.) Message Digest", "3.) Multicast", "4.) Join", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (120, "You are designing an iFlow and one of the requirements is to invoke an external OData service to update the message. What step type should you use?", "1.) Send", "2.) Request Reply", "3.) Content Enricher", "4.) Content Modifier", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (121, "Which tool or service do can you use to link SAP Cloud Platform applications and On-premise systems together?", "1.) Cloud Integration", "2.) SAP HANA smart data integration", "3.) SAP Business Connector", "4.) SAP Cloud Connector", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (122, "You want to modify a message using code. Which languages can you use? (2 correct)", "1.) Swift", "2.) C+ +", "3.) Groovy", "4.) JavaScript", NULL, NULL, "3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (123, "You want to connect a third-party application to an SAP BTP landscape, via an Open Connector provided by the SAP Integration Suite. What must you do first?", "1.) Create an instance of the required connector.", "2.) Test the required connector.", "3.) Download the connector artifacts and import them into the SAP Open Connectors.", "4.) Create a custom implementation for the connector.", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (124, "Which of the following are principles of cloud computing? (2 correct)", "1.) Microservices", "2.) Automation", "3.) Serverless", "4.) Integration", NULL, NULL, "1,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (125, "What features can you use in SAP Cloud Integration, DataStoreOperations? (2 correct)", "1.) Delete", "2.) Get", "3.) Put", "4.) Post", NULL, NULL, "1,2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (126, "SAP Cloud Platform Integration is based on the Apache Camel integration framework. What is a feature of this integration framework?", "1.) It is a payload free routing and mediation engine.", "2.) It is a payload agnostic routing and mediation engine.", "3.) It is a routing and mediation engine for only XML payload.", "4.) It is a metadata payload routing and mediation engine.", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (127, "In the SAP BTP cockpit, what functionality does a destination for Cloud Integration enable?", "1.) Invoking function modules in on-premise ABAP systems via RFC from cloud applications", "2.) Establishing connections between Integration Suite capabilities", "3.) Consuming cloud applications in an on-premise back-end system via HTTP(S)", "4.) Sending e-mails from web applications using public e-mail providers", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (128, "Where do you define permissions for senders to process messages on a runtime node?", "1.) SAP Cloud Platform > Members", "2.) SAP Solution Manager", "3.) SAP Cloud Platform > Security > Authorizations", "4.) SAP Cloud Platform Integration Manage Security", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (129, "What actions can you perform when creating a product in SAP API Management? (2 correct)", "1.) Publish", "2.) Deploy", "3.) Save As Draft", "4.) Save", NULL, NULL, "1,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (130, "You want to use SAP Cloud Platform Integration content for different integration platforms. What do you do to the product profiles?", "1.) Use the SAP Cloud Platform Integration product profile for all target integration platforms.", "2.) Change the product profile to your target platform on SAP Cloud Platform Integration.", "3.) It works out of the box for all integration platforms.", "4.) Change the product profile on the target platform.", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (131, "You want to transform an inbound message to a specific structure that is needed in the outbound system. What mapping types can you use? (3 correct)", "1.) AI-based mapping", "2.) XSLT mapping", "3.) Excel spreadsheet mapping", "4.) Operation mapping", "5.) Message mapping", NULL, "2,4,5");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (132, "What is required to access API Business Hub Enterprise?", "1.) SAP API Business Hub", "2.) SAP Business Application Studio", "3.) SAP Extension Suite", "4.) SAP Integration Suite", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (133, "What are some SAP Business Technology Platform features? (2 correct)", "1.) Application development using SAP Extension Suite", "2.) SAP Analytics Cloud integration", "3.) Third-party database systems extension", "4.) Application development in SAP on-premise systems", NULL, NULL, "1,2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (134, "Which of the following are primary capabilities of SAP Cloud Platform? (3 correct)", "1.) It enriches an SAP HANA database", "2.) It integrates cloud applications.", "3.) It is positioned as the SAP SaaS platform.", "4.) It extends On-premise applications", "5.) It is an agile platform.", NULL, "1,2,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (135, "Why are Message Implementation Guidelines (MIGs) focused on semantics? (2 correct)", "1.) To understand how information is used in different scenarios and business domains", "2.) To improve translation of data objects", "3.) To understand the meaning and properties of customized interface elements in a given business context", "4.) To improve internationalization of data elements", NULL, NULL, "1,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (136, "Which call types can you use to invoke local integration processes through their parent iFlow? (2 correct)", "1.) Node process call", "2.) Looping process call", "3.) Process call", "4.) Child process call", NULL, NULL, "2,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (137, "You are using the HTTP adapter to connect to a third-party cloud software. Which operations are supported? (2 correct)", "1.) HEAD", "2.) OPTIONS", "3.) TRACE", "4.) PURGE", NULL, NULL, "1,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (138, "Your iflow processes messages synchronously and you get the message status ESCALATED. What does this message status mean?", "1.) NO error message is sent to the sender.", "2.) An error message is sent to the sender.", "3.) An error message is sent to the receiver.", "4.) NO error message is sent to the receiver.", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (139, "Which of the following are components of the SAP Integration Suite? (2 correct)", "1.) Cloud Integration", "2.) Automation Pilot", "3.) Continuous Integration & Delivery", "4.) Integration Advisor", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (140, "What can you create in SAP Integration Suite API Management? (2 correct)", "1.) API Proxies", "2.) API Connectors", "3.) API Portals", "4.) API Providers", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (141, "What can you use to deploy a cloud native micro app? Please choose the correct answer. Choose one", "1.) SAP Cloud Platform, Neo environment", "2.) SAP Cloud Platform, Cloud Foundry environment", "3.) SAP HANA Enterprise Cloud", "4.) ABAP stack", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (142, "Which service components are included in the Platform as a Service (PaaS) model? (2 correct)", "1.) Data", "2.) Middleware(s)", "3.) Runtime(s)", "4.) Networking services", NULL, NULL, "2,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (143, "What can you map with the message mapping transformer?", "1.) Input to output message encoding", "2.) Properties to messages", "3.) XSLT to JSON format", "4.) Input to output message structures", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (144, "Which of the following capabilities are included with DevOps services? (3 correct)", "1.) Enrichment", "2.) Configuration", "3.) Monitoring", "4.) Deployment", "5.) Scaling", NULL, "2,3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (145, "You have created a custom business object in SAP S/4HANA How can you access this object outside of SAP S/4HANA?", "1.) Via an SAP S/4HANA OData interface", "2.) Via an SAP S/4HANA Soap interface", "3.) Via an SAP API Business Hub interface", NULL, NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (146, "You want to add a header variable to an exchange message. What type is NOT supported?", "1.) Regular Expression", "2.) Xpath", "3.) Global Variable", "4.) Expression", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (147, "What is the fastest way to validate the quality of a Mapping Guideline (MAG)?", "1.) Simulating and reviewing the results with previously provided sample output values", "2.) Simulating and reviewing the results with automatically generated sample values", "3.) Simulating and reviewing the results with previously provided sample input values", NULL, NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (148, "You want to break down a composite message into a series of individual messages. Which standard splitting methods are available? (2 correct)", "1.) IDoc Splitter", "2.) Mail Splitter", "3.) JSON Splitter", "4.) PKCS#7/CMS Splitter", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (149, "For which of the following does the Integration Advisor Proposal Service provide suggestions?", "1.) How to combine message mappings", "2.) Working with simulation values and their outcomes", "3.) Working with XSLT, JavaScript, and Groovy scripts", "4.) How to customize an interface", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (150, "Which of the following are characteristics of the cloud native process model? (2 correct)", "1.) Continuous delivery", "2.) Use of containers", "3.) Client server", "4.) Waterfall", NULL, NULL, "1,2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (151, "Which of the following is a valid sequence of steps to incorporate information from an external source into an iFlow?", "1.) Add external call \"Request Reply\". Add process participant \"Receiver\". Connect \"Request Reply\" with \"Receiver\". Choose an appropriate adapter type.", "2.) Add external call \"Send\". Add process participant \"Receiver\". Connect \"Send\" with \"Receiver\". Choose an appropriate adapter Utype", "3.) Add external call \"Request Reply\". Add process participant \"Sender\". Connect \"Request Reply\" with \"Sender\". Choose an appropriate adapter type", NULL, NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (152, "Which capability of the SAP Integration Suite can you use to provide processed data to other applications and consumers?", "1.) SAP Integration Advisor", "2.) SAP Cloud Integration", "3.) SAP API Management", "4.) SAP Open Connectors", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (153, "How do SAP Data Centers operate? (2 correct)", "1.) It runs explicitly in Germany.", "2.) It runs also in secure environments.", "3.) It runs at multiple locations around the world.", "4.) It runs only in secure and certified environments.", NULL, NULL, "3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (154, "You want to debug your iFlow at run time. What log level do you use if you want to check the payloads at every process step?", "1.) Debug", "2.) Trace", "3.) Info", "4.) Create a script", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (155, "What is the main feature of the Low/No-Code programming model in SAP Business Technology Platform?", "1.) Working graphically", "2.) Using APIs and special libraries for easier and more secure programming", "3.) Working with all known cloud patterns", NULL, NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (156, "Every SAP Cloud Platform Integration tenant has at least one tenant management node and one runtime node. Which of the following tasks does the tenant management node perform? (2 correct)", "1.) It Processes messages that are exchanged", "2.) It interacts with data storage", "3.) It reads the data from the database for monitoring.", "4.) It starts and stops runtime nodes.", NULL, NULL, "3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (157, "Which of the following does a Message Implementation Guideline (MIG) describe? (2 correct)", "1.) The validation of payloads via XSD", "2.) The meaning of each defined element", "3.) The structure of a customized interface", "4.) The mappings between source and target code values", NULL, NULL, "3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (158, "You want to use outbound communication based on HTTPS. Which authentication options do you have? (2 correct)", "1.) Basic authentication", "2.) Client-certificate authentication", "3.) Two-factor authentication", "4.) Root-certificate authentication", NULL, NULL, "1,2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (159, "What happens to the log level of an iFlow when this iFlow is deleted from the system?", "1.) The log level is kept.", "2.) The log level is set to None.", "3.) The log level is set to the default value.", "4.) The log level is removed.", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (160, "What are some characteristics of SAP Integration Suite capabilities? (2 correct)", "1.) Integration Advisor can be used to automatically create iFlows in Cloud Integration.", "2.) SAP Open Connectors can act as an API Provider for API Management.", "3.) SAP Open Connectors can be used to create iFlows in Integration Advisor.", "4.) APIs published in API Management can be used in iFlows in Cloud Integration.", NULL, NULL, "2,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (161, "What do you need to specify in the connection when you add an API provider in SAP Open Connectors?", "1.) API key", "2.) Policy template", "3.) Organization secret and user secret", NULL, NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (162, "While testing your iFlow you discover that a data store operation step fetches multiple messages instead of one. What data store operation step type will fetch a specific message from the data store?", "1.) Get", "2.) Delete", "3.) Select", "4.) Write", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (163, "You want to use an inbound SOAP adapter for synchronous communication. What SOAP version can you use?", "1.) SOAP 1.x", "2.) SAP RM", "3.) All available SOAP versions", "4.) SOAP WS-RM", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (164, "In an SAP Cloud Integration iFlow you want to compress message content into a ZIP archive. Which of the following message transformer steps do you use?", "1.) Converter", "2.) Decoder", "3.) Encoder", "4.) Content Modifier", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (165, "Your client is unsure of how SAP Cloud Platform enhances SAP S/4HANA and needs more information. What additional capabilities does a customer gain if they have SAP Cloud Platform along with SAP S/4HANA? (3 correct)", "1.) Perform in-app extensibility.", "2.) Use extension services.", "3.) Create new standalone cloud apps.", "4.) Platform side-by-side extensibility.", "5.) Integrate with SAP Cloud apps third-party solutions.", NULL, "3,4,5");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (166, "What is a connector in SAP Open Connectors?", "1.) A custom-built integration flow with a third-party provider", "2.) A pre-built API integration with a third-party provider", "3.) A custom-built API integration with a third-party provider", "4.) A pre-built integration flow with a third-party provider", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (167, "What information can you provide to the Integration Advisor to enhance the validity of proposals? (3 correct)", "1.) Workflow role", "2.) Location information", "3.) Business context", "4.) Industry classification", "5.) Technical context", NULL, "2,3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (168, "What are the characteristics of the Authorization and Trust Management service in the SAP Cloud Platform, cloud foundry environment (XSUAA)? (2 correct)", "1.) It works only with SAML 2.0.", "2.) It manages authentications.", "3.) It acts as an OAuth provider for a microapp.", "4.) It provides JSON web tokens.", NULL, NULL, "3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (169, "What are the main features of SAP Data Quality Management? (2 correct)", "1.) Address cleaning", "2.) Geocoding", "3.) Automated analysis", "4.) Platform to create a business service packages", NULL, NULL, "1,2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (170, "In SAP Cloud Integration, what Datastore Operations control do you use to specify the number of polled messages to send to the receiver?", "1.) Read", "2.) Select", "3.) Join", "4.) Fetch", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (171, "Which transport and message protocols are used with an inbound IDoc adapter?", "1.) tRFC and IDoc", "2.) HTTP(s) and SOAP", "3.) HTTP(s) and IDoc", "4.) tRFC and SOAP", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (172, "Which of the following adapter types are available for a sender to transfer a message to SAP Cloud Platform Integration? (2 correct)", "1.) SAP Success factors", "2.) SAP Ariba", "3.) Twitter", "4.) Face book", NULL, NULL, "1,2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (173, "Which service components are included in the Infrastructure as a Service (IaaS) model? (2 correct)", "1.) Storage", "2.) Data", "3.) Runtime", "4.) Virtualization", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (174, "In SAP Cloud Integration, which decoding schemes are available to decode a message? (2 correct)", "1.) GZIP Decompression", "2.) CNN-based Decoder", "3.) QC-MDPC Decoding", "4.) Base64 Decoder", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (175, "Where do you create a Slack instance?", "1.) In the Integration Advisor", "2.) In SAP Cloud Integration", "3.) In SAP Open Connectors", "4.) In the API portal", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (176, "Which incoming formats are available for the aggregation strategy in a Gather step type? (2 correct)", "1.) ASCII", "2.) Plain Text", "3.) XML (Different Format)", "4.) JSON", NULL, NULL, "2,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (177, "To what service model does the SAP Cloud Platform Integration service belong?", "1.) A standalone app", "2.) A service on an SaaS", "3.) A service on an IaaS", "4.) A service on a PaaS", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (178, "In SAP Cloud Integration, what are some element types of an iFlow? (2 correct)", "1.) Events", "2.) Mapping Guidelines (MAG)", "3.) Senders and receivers", "4.) Integration artifacts", NULL, NULL, "1,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (179, "What can you use to transport your iFlow from DEV to PROD? (2 correct)", "1.) BRF+", "2.) MTAR download", "3.) MTA download", "4.) CTS+", NULL, NULL, "2,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (180, "In SAP Cloud Integration, what converter options are available to convert a message from one format to another in one step? (2 correct)", "1.) JSON -> XML", "2.) XML -> EDI", "3.) CSV -> JSON", "4.) EDI -> CSV", NULL, NULL, "1,2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (181, "You want to encode/compress messages. Which schemes can you use? (2 correct)", "1.) GZIP Compression", "2.) RAR Compression", "3.) Base64 Encoder", "4.) 7plus Encoder", NULL, NULL, "1,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (182, "Your iFlow builds a payload and sends it to another system. You have activated the Trace log level. In the Message Processing Monitor, what must you investigate to find this payload?", "1.) iFlow data", "2.) Artifact details", "3.) iFlow Message Outcome", "4.) Message content", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (183, "What does the \"Open integration\" principle of the SAP Integration Suite mean?", "1.) SAP software by default supports any third-party integration.", "2.) SAP's integration technology portfolio covers all kinds of integration.", "3.) SAP software by default supports integrations to other SAP software.", NULL, NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (184, "What is the integration style that SAP Cloud Platform Integration follows?", "1.) Data Movement", "2.) Thing Integration", "3.) User Centric Consumption", "4.) Process Invocation", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (185, "You want to allow a new developer to access the design view of your SAP Cloud Platform Integration tenant. Where do you set these access rights?", "1.) SAP Cloud Platform Integration tenant settings", "2.) SAP Solution Manager", "3.) SAP identity provider", "4.) SAP Cloud Platform", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (186, "What predefined role is necessary to send HTTPS-based messages to an SAP Cloud Platform Integration endpoint?", "1.) Message.send", "2.) HttpMessaging.send", "3.) ESB Messaging.send", "4.) Inbound Message.send", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (187, "When you want to try out APIs on SAP API Business Hub, which of the following is the default test environment?", "1.) Sandbox", "2.) Climbing frame", "3.) Testing ground", "4.) Playground", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (188, "Which of the following components are provided by SAP Business Technology Platform environments? (3 correct)", "1.) Runtime", "2.) Tools", "3.) Applications", "4.) Services", "5.) Systems", NULL, "1,3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (189, "What kind of editor do you use to manipulate iFlows?", "1.) Command-line editor", "2.) Graphical editor", "3.) Code editor", NULL, NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (190, "What must you assign so that a user can access an SAP Integration Suite capability?", "1.) Role templates to the user", "2.) The user to the SAP Integration Suite", "3.) The user to the SAP integration Suite capability", "4.) Role collections to the user", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (191, "What can you do in SAP Integration Suite, Cloud Integration? (2 correct)", "1.) Connect to different cloud runtime environment", "2.) Develop complex integration scenarios in Python", "3.) Connect to multiple endpoints", "4.) Develop custom adapters", NULL, NULL, "3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (192, "Your client is evaluating an SAP HANA Enterprise Cloud purchase and needs more information options. Which of the following SLA options cover SAP HANA Enterprise Cloud Productive infrastructure?", "1.) Digital Business Services", "2.) Standard Technical Services", "3.) Application Management Services", "4.) Enhanced Management Services", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (193, "Where in SAP Integration Suite Open Connectors can you test connector instances?", "1.) Validation", "2.) Setup", "3.) Resources", "4.) API docs", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (194, "You want to use a Groovy script to modify the headers of an exchange message. What import library must you use?", "1.) com.sap.gateway.ip.core.customdev.util.Message;", "2.) com.sap.gateway.integration.flow.Message;", "3.) com.sap.gateway.xiinspector.xml. Message;", "4.) com.apache.camel.framework.util.Message;", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (195, "Which of the following are integrated solutions of SAP's Business Technology Platform? (2 correct)", "1.) Blockchain", "2.) Development and Deployment", "3.) Analytics", "4.) Application Development and Integration", NULL, NULL, "3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (196, "Your client is using SAP Hybris for sales order quotes. A large percentage of customers registered in SAP Hybris have duplicate addresses. What SAP Cloud Platform service do you recommend to cleanse the customer address?", "1.) SAP Hybris as a Service (YaaS) on SAP Cloud Platform", "2.) SAP Cloud Platform Business Rules service", "3.) SAP Data Quality Management. Micro services for location data", "4.) SAP Cloud Platform Identity Provisioning", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (197, "To call an application in the SAP API Business Hub, what do you need?", "1.) User secret", "2.) API Key", "3.) Certificate", NULL, NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (198, "Your client is unsure about the possible options to implement their cloud transformation journey and needs more information. Which of the following products are cloud transformation options? (3 correct)", "1.) SAP Cloud Platform", "2.) SAP HANA Enterprise Cloud", "3.) SAP Cloud Trust Center", "4.) SAP Cloud Connector", "5.) SAP cloud apps (SAP SuccessFactors, SAP Concur, etc.)", NULL, "1,2,5");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (199, "When you create a Message Implementation Guideline (MIG), you can choose directions. Which direction must you choose for a system to receive and process payloads?", "1.) Custom", "2.) Out", "3.) In", NULL, NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (200, "You want to send messages over an SOAP adapter to an integration flow. Which method do you use to send the messages?", "1.) UPDATE", "2.) PATCH", "3.) GET", "4.) POST", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (201, "Where can you configure a static payload? (2 correct)", "1.) In a Data Store Operation component", "2.) In a Content Modifier component of the Message Body tab", "3.) In a Content Modifier component of the Message Header tab", "4.) In a Groovy script", NULL, NULL, "1,2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (202, "You want to implement a synchronous call to a remote HTTP API as an integration flow component. Which adapter can you use?", "1.) OData", "2.) Mail", "3.) AMQP", "4.) SFTP", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (203, "Which data store operation can you use to save a customer ID?", "1.) GET", "2.) SELECT", "3.) POST", "4.) WRITE", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (204, "What can you do in the Cloud Integration capability within SAP Integration Suite? (2 correct)", "1.) Connect to different cloud runtime environments.", "2.) Connect to multiple endpoints.", "3.) Develop custom adapters.", "4.) Develop complex integration scenarios in Python.", NULL, NULL, "2,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (205, "You have set up an integration process to use a SOAP adapter. Which event allows you to run the integration flow directly after deployment?", "1.) End Event", "2.) End Message", "3.) Start Event", "4.) Start Message", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (206, "Which expression language can you use to access the content of a message in an integration flow?", "1.) JavaScript expression language", "2.) XML expression language", "3.) Spring expression language", "4.) Simple expression language", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (207, "You use an outbound HTTP adapter with basic authentication. In SAP Integration Suite, Monitor Integrations Manage Security, where must you set up and store a user and password?", "1.) Security Material", "2.) Access policies", "3.) PGP Keys", "4.) Keystore", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (208, "You use an API Key for authentication in an HTTPS API call. In which part of the Content Modifier is the API Key included?", "1.) Message body", "2.) Message header", "3.) Attachment", "4.) Exchange property", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (209, "What are the key capabilities of the SAP BTP Integration Suite? (2 correct)", "1.) API Management", "2.) Connectivity Service", "3.) Open Connectors", "4.) SAP Business Application Studio", NULL, NULL, "1,2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (210, "In which of the following must you call getBody() to access the payload in a Groovy script?", "1.) camelcontext", "2.) property", "3.) header", "4.) message", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (211, "You configured a content modifier as follows: Action Create. Name: ProductID. Source Type: XPath. Source Value: //ProductID. Data Type: java lang string. After testing the content modifier, you receive an error message that contains the following fragment: java.lang.ClassNotFoundException java lang string. What caused the error message?", "1.) Incorrect name", "2.) Incorrect source value", "3.) Incorrect source type", "4.) Incorrect data type", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (212, "What is Representational State Transfer (REST)?", "1.) An architectural style", "2.) A description language for APIs", "3.) A message protocol", "4.) An application protocol", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (213, "Which of the following are markup languages that you can use to describe APIs? (2 correct)", "1.) RAML", "2.) CXML", "3.) Open API", "4.) HTML", NULL, NULL, "1,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (214, "You want to use an HTTPS endpoint from an integration flow. In which of the following must you use the HTTP client?", "1.) API Management capability within SAP Integration Suite", "2.) Open Connectors capability within SAP Integration Suite", "3.) SAP Integration Suite, advanced event mesh", "4.) SAP Business Application Studio", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (215, "You want to call an OData v4.0 interface through an adapter in the Cloud Integration capability within SAP Integration Suite. Which adapter can you use?", "1.) JMS", "2.) ProcessDirect", "3.) HTTPS", "4.) SOAP", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (216, "You want to access individual entities of an HTTP call over XPath.What must you do if no namespace mapping exists?", "1.) Convert the namespaces to JSON.", "2.) Remove the namespaces.", "3.) Convert the namespaces to XML", "4.) Remove the XML prolog.", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (217, "You want to integrate a SOAP adapter into an integration process and enable the adapter to send messages to the integration flow. Which user role must you set up in the SOAP adapter?", "1.) MessagingsendtoCI", "2.) MessagingSend", "3.) ESBMessaging send", NULL, NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (218, "How do you configure a SOAP adapter for asynchronous processing?", "1.) Message Exchange Pattern: Request-Reply Process Settings Robust", "2.) Message Exchange Pattern: Request-Reply Process Settings WS Standard", "3.) Message Exchange Pattern: One-Way Process Settings: Robust", "4.) Message Exchange Pattern: One-Way Process Settings: WS Standard", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (219, "Which of the following capabilities within SAP Integration Suite are core for integration? (3 correct)", "1.) Integration Advisor", "2.) Open Connectors", "3.) Integration Assessment", "4.) Cloud Integration", "5.) API Management", NULL, "3,4,5");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (220, "When does the \"Trace\" log level expire and when will the log files be removed?", "1.) Expiration. 10 minutes Removal. After 24 hours", "2.) Expiration: 15 minutes Removal: After 24 hours", "3.) Expiration: 15 minutes Removal: After 10 hours", "4.) Expiration: 10 minutes Removal: After 1 hour", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (221, "What are some advantages of creating an OData interface through an API provider? (2 correct)", "1.) Automatic creation of a WSDL specification", "2.) Automatic creation of a RAML specification", "3.) Automatic creation of a Swagger UI", "4.) Automatic creation of an openAPI specification", NULL, NULL, "3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (222, "Which part of the proxy URL is provided by the initial configuration step of the API Management?", "1.) Name of the API management", "2.) Service name", "3.) Version", "4.) Virtual host", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (223, "Where must you configure an HTTPS inbound adapter with OAuth 2.0 authentication?", "1.) In the adapter", "2.) In the integration flow", "3.) In the SAP Integration Suite", "4.) In the process runtime", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (224, "You are creating an API in the API management capability within SAP Integration Suite using Edit in API Designer. What is the next step to consolidate the resources?", "1.) Generate the server stubs", "2.) Generate the database tables.", "3.) Generate the client stubs", "4.) Generate the microservices.", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (225, "In the SAP Integration Suite, where can you change the virtual host name?", "1.) Discover - APIs", "2.) Design APIs", "3.) Configure ? APIs", "4.) Settings APIs", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (226, "You want to publish a new API product to the API business hub enterprise. What is a requirement?", "1.) At least two deployed API Providers", "2.) At least one deployed API Proxy", "3.) At least one deployed API Provider", "4.) At least two deployed API Proxies", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (227, "Where can you find more information about APIs, policies, and integrations?", "1.) Cloud Integration capability within SAP Integration Suite", "2.) Open Connectors capability within SAP Integration Suite", "3.) SAP Business Accelerator Hub", NULL, NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (228, "In your integration flow process, the request reply returns a message with namespaces. What can you do to delete namespaces from this message? (2 correct)", "1.) Set up the request reply to delete the namespaces", "2.) Use a Content Modifier", "3.) Set up the namespace mapping in the Runtime Configuration.", "4.) Use an XSLT mapping.", NULL, NULL, "2,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (229, "You have created an API provider of the type Internet. What http response code indicates success?", "1.) 203", "2.) 403", "3.) 200", "4.) 401", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (230, "You want to set up an SAP backend system through the Cloud Connector with an API provider. Which connection type do you use?", "1.) Internet", "2.) On-premise", "3.) Cloud Integration", "4.) Open Connectors", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (231, "Which SAP Cloud Integration process event allows you to run integration flows directly after deployment?", "1.) Content Modifier", "2.) Router", "3.) Message Digest", "4.) Timer", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (232, "What does an API consumer do?", "1.) It provides the server-side implementation of an interface.", "2.) It invokes an interface.", "3.) It provides an interface.", NULL, NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (233, "What are some message protocols that the API Management capability within SAP Integration Suite supports? (3 correct)", "1.) SOAP", "2.) RFC", "3.) REST", "4.) OData", "5.) IDoc", NULL, "1,3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (234, "In the Cloud Integration capability within SAP Integration Suite, which internal message format is used?", "1.) XML", "2.) JSON", "3.) XSLT", NULL, NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (235, "You want to dispatch messages only when a child element \"Product\" exists. Which condition do you set?", "1.) ProductSet/count(Product)>0", "2.) /ProductSet/count(Product)=0", "3.) /ProductSet/count(Product)<0)", "4.) /ProductSet/counter(Product)>0", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (236, "Besides in SAP API Management, where can you find policy templates?", "1.) In SAP API Business Accelerator Hub - Explore Discover Integrations", "2.) In SAP API Business Accelerator Hub- Explore Categories ?? APIs", "3.) In SAP API Business Accelerator Hub ? Explore Business Processes", "4.) In SAP API Business Accelerator Hub- Explore Products", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (237, "What can you use to prevent overload in an OData request and reply call?", "1.) Query filter", "2.) HTTP adapter", "3.) Stop parameter", "4.) Paging", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (238, "What are some aspects of \"holistic integration\" of the SAP Integration Suite? (3 correct)", "1.) Process Integration", "2.) Cloud Integration", "3.) Event Integration", "4.) Domain Integration", "5.) Data Integration", NULL, "1,3,5");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (239, "What must you do to find out which entity sets are available in the OData V2.0 interface?", "1.) Retrieve the service document from the interface.", "2.) Retrieve the metadata document from the interface.", "3.) Contact the OData interface manufacturer", "4.) Search in the Global Directory of all available OData interfaces.", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (240, "Using the Test Connectivity function, you want to test a connection to a backend system. The connection is provided by a Cloud Connector. Which parameter is required for the connection test?", "1.) Connector ID", "2.) Host", "3.) Location ID", "4.) Subaccount ID", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (241, "You are using a Data store Operation of the type Write. Which parameter must you select to avoid duplicate entries?", "1.) Overwrite Existing Message", "2.) Retention Threshold for Alerting", "3.) Include Message Headers", "4.) Encrypted stored Message", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (242, "You want to split a message that contains recurring child nodes. Which of the following splitter types can you use? (2 correct)", "1.) EDI Splitter", "2.) PKCS#7/CMS Splitter", "3.) General Splitter", "4.) Iterating Splitter", NULL, NULL, "3,4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (243, "You want to set up Exchange Properties in an integration flow. Besides a Content Modifier, what can you use?", "1.) Python scripting", "2.) Groovy SDK scripting", "3.) Batch scripting", "4.) XML scripting", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (244, "You want to build an architecture that is largely asynchronous. Which design do you use to exchange notifications between the partners involved?", "1.) Event-driven design", "2.) Hexagonal design", "3.) Serverless design", "4.) Request-driven design", NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (245, "What is a characteristic of a product in the API Management capability within SAP Integration Suite?", "1.) It encapsulates the API provider.", "2.) It is a separate artifact and is required for basic authentication.", "3.) It is deployed as a separate artifact on the API business hub enterprise", NULL, NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (246, "Which functionalities are used by OData?", "1.) HTTP. AtomPub, and JSON", "2.) TCP. AtomPub, and JSON", "3.) SOAP, AtomPub, and JSON", NULL, NULL, NULL, "1");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (247, "What are the maturity levels of the SAP Integration Solution Advisory Methodology? (2 correct)", "1.) Enable your integration structure.", "2.) Design your hybrid integration platform.", "3.) Assess your integration strategy", "4.) Implement your integration architectural strategy.", NULL, NULL, "2,3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (248, "What do you use in an integration flow to handle unexpected errors?", "1.) Status code checks", "2.) Exception handler integration flow elements", "3.) Try-catch subprocesses", "4.) Exception-handling subprocesses", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (249, "What are target endpoints of an API? (3 correct)", "1.) API provider", "2.) API consumer", "3.) Resources", "4.) API proxy", "5.) URL of original API", NULL, "1,4,5");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (250, "What does the messaging model of the Apache Camel Data Model consist of?", "1.) Header, Exchange ID, in-message", "2.) Header, body, attachment", "3.) Header, body, properties", "4.) Header, properties, attachment", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (251, "Which log level must you use to examine the payload at specific processing steps in an integration flow?", "1.) Error", "2.) Debug", "3.) Trace", "4.) Info", NULL, NULL, "3");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (252, "Which of the following can you use for an XSLT mapping in an integration flow?", "1.) HTML", "2.) JSON", "3.) PHP", "4.) XML", NULL, NULL, "4");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (253, "You have set up a basic authentication policy, but the API proxy returns an HTTP status of 401. What could be a reason?", "1.) In the AssignMessage policy, the AssignTo tag has the type=\"postFlow\"", "2.) In the AssignMessage policy, the Assign To tag has the type=\"response\"", "3.) In the AssignMessage policy, the AssignTo tag has the type=\"request\"", "4.) In the AssignMessage policy, the AssignTo tag has the type=\"preflow\"", NULL, NULL, "2");
INSERT INTO questions (id, question, option1, option2, option3, option4, option5, option6, correct) VALUES (254, "In a Content Modifier, you want to set up a call to the message body of the previous Content Modifier. Which notation do use to implement this?", "1.) S(inbody)", "2.) S[bodyin]", "3.) S{in body)", "4.) S{body.in}", NULL, NULL, "3");
